provider_config:
  bms:
    ssh_pwd: c0ntrail123
    ssh_user: root
    ntpserver: 10.6.8.254
    domainsuffix: poc
instances:
  cmaster-1:
    provider: bms
    ip: 10.6.8.61
    roles:
      config_database:
      config:
      control:
      analytics_database:
      analytics:
      webui:
      kubemanager:
      k8s_master:
  node-1:
    provider: bms
    ip: 10.6.8.67
    roles:
      vrouter:
      k8s_node:
  node-2:
    provider: bms
    ip: 10.6.8.68
    roles:
      vrouter:
      k8s_node:
global_configuration:
  CONTAINER_REGISTRY: hub.juniper.net/contrail
  CONTAINER_REGISTRY_USERNAME: __registry_username__
  CONTAINER_REGISTRY_PASSWORD: __registry_password__
contrail_configuration:
  CONTRAIL_VERSION: __contrail_version__
  CONTRAIL_CONTAINER_TAG: __contrail_tag__
  CLOUD_ORCHESTRATOR: kubernetes
  CONTROLLER_NODES: 10.6.11.61
  CONTROL_NODES: 10.6.11.61
  WEBUI_NODES: 10.6.8.61
  VROUTER_GATEWAY: 10.6.11.254
  CONFIG_DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: 20
  DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: 20

