#!/bin/bash

# Configuration
host_username=root
host_password=c0ntrail123
contrail_version=__contrail_version__
registry_username=__registry_username__
registry_password=__registry_password__
ntp_server=10.6.8.254

registry_url=hub.juniper.net/contrail
contrail_deployer=contrail-kolla-ansible-deployer
contrail_deployer_image=$registry_url/$contrail_deployer:$contrail_version
command_deployer=contrail-command-deployer
command_deployer_image=$registry_url/$command_deployer:$contrail_version

get_host_address()
{
    local a_p
    local a

    host_interface=$(ip route | awk "/default/"'{ print $5}')
    a_p=$(ip -f inet -br addr show dev $host_interface | awk '{ print $3 }')
    IFS='/'; a=(${a_p}); unset IFS
    host_address=${a[0]}
}

install_docker()
{
    echo "Install Docker CE..."
    rpm -q docker-ce-18.06.1.ce > /dev/null 2>&1
    if (( $? == 0 )); then
        return
    fi
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager \
        --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum install -y docker-ce-18.06.1.ce
    systemctl enable docker
    systemctl start docker
}

pull_image()
{
    local image=$1

    echo "Pull $image..."
    docker image list | grep $image > /dev/null 2>&1
    if (( $? == 0 )); then
        return
    fi
    docker login hub.juniper.net \
            --username $registry_username \
            --password $registry_password
    docker pull $image
}

launch_deployer()
{
    echo "Launch deployer..."
    docker ps | grep $contrail_deployer > /dev/null 2>&1
    if (( $? == 0 )); then
        return
    fi
    docker run -td --net host --name contrail_kolla_ansible_deployer \
            $contrail_deployer_image
}

build_instances_yaml()
{
    cat << __EOF__ > instances.yaml
provider_config:
  bms:
    ssh_user: $host_username
    ssh_pwd: $host_password
    ntpserver: $ntp_server
    domainsuffix: bootstrap
instances:
  bootstrap:
    provider: bms
    ip: $host_address
    roles:
      config_database:
      config:
      control:
      analytics:
      analytics_alarm:
      analytics_snmp:
      analytics_database:
      webui:
      dhcp:
global_configuration:
  CONTAINER_REGISTRY: $registry_url
  CONTAINER_REGISTRY_USERNAME: $registry_username
  CONTAINER_REGISTRY_PASSWORD: $registry_password
contrail_configuration:
  CONTRAIL_VERSION: $contrail_version
  CONTRAIL_CONTAINER_TAG: $contrail_version
  CLOUD_ORCHESTRATOR: none
  ENCAP_PRIORITY: VXLAN,MPLSoUDP,MPLSoGRE
  CONFIG_DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: 20
  DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: 20
  AAA_MODE: no-auth
  # With no-auth, config_dnsmasq_1 still needs these env vars.
  KEYSTONE_AUTH_HOST: $host_address
  KEYSTONE_AUTH_ADMIN_PASSWORD: contrail123
  KEYSTONE_AUTH_ADMIN_USER: admin
  KEYSTONE_AUTH_ADMIN_TENANT: admin
__EOF__
}

check_playbook_result()
{
    local rc_list
    local rc

    rc_list=$(tail -n 80 bootstrap.log | grep -A 30 "PLAY RECAP" | \
            awk "/failed/"'{print $6}')
    for rc in $rc_list; do
        if [ "$rc" != "failed=0" ]; then return 1; fi
    done
}

run_playbook()
{
    local pb_list=$1
    local dst

    exec > >(tee bootstrap.log)
    exec 2>&1
    echo "Deploy..."

    build_instances_yaml
    dst=/root/contrail-ansible-deployer/config/instances.yaml
    docker cp instances.yaml contrail_kolla_ansible_deployer:$dst
    for pb in $pb_list; do
        echo "Run playbook $pb..."
        docker exec contrail_kolla_ansible_deployer bash -c \
                "cd /root/contrail-ansible-deployer;
                 ansible-playbook -i inventory playbooks/$pb"
        check_playbook_result; if (( $? )); then return 1; fi
    done
}

build_command_conf()
{
    cat << __EOF__ > command_servers.yml
---
command_servers:
    server1:
        ip: $host_address
        connection: ssh
        ssh_user: $host_username
        ssh_pass: $host_password
        sudo_pass: $host_password
        ntpserver: $ntp_server

        container_registry: $registry_url
        registry_insecure: false
        container_tag: "$contrail_version"
        container_registry_username: $registry_username
        container_registry_password: $registry_password

        config_dir: /etc/contrail

        contrail_config:
            database:
                password: contrail123
            server:
                address: ":9091"
            keystone:
                local: true
                assignment:
                    type: static
                    data:
                      domains:
                        default: &default
                          id: default
                          name: default
                      projects:
                        admin: &admin
                          id: admin
                          name: admin
                          domain: *default
                      users:
                        admin:
                          id: admin
                          name: admin
                          domain: *default
                          password: contrail123
                          email: admin@juniper.nets
                          roles:
                          - id: admin
                            name: admin
                            project: *admin
                store:
                    type: memory
                    expire: 3600
                insecure: true
                authurl: https://localhost:9091/keystone/v3
            no_auth: true
            insecure: true
            client:
              id: admin
              password: contrail123
              project_id: admin
              domain_id: default
              schema_root: /
              endpoint: https://localhost:9091
__EOF__
}

check_command()
{
    local rc_list
    local rc

    let "count = 2"
    while (( $count > 0  )); do
        sleep 10
        echo "Check Contrail Command Deployer..."
        docker logs --tail 10 contrail_command_deployer | \
                grep "PLAY RECAP" > /dev/null 2>&1
        if (( "$?" == "0" )); then
            let "count -= 1"
        fi
    done

    docker logs --tail 10 contrail_command_deployer | \
            grep -A 10 "PLAY RECAP" | awk "/failed/"'{print}'
}

launch_command()
{
    build_command_conf
    docker run -t --net host -d --privileged \
            -e orchestrator=kubernetes \
            -e action=import_cluster \
            -v /root/instances.yaml:/instances.yml \
            -v /root/command_servers.yml:/command_servers.yml \
            --name contrail_command_deployer \
            $command_deployer_image
    check_command
    systemctl status iptables > /dev/null 2>&1
    if (( $? == 0 )); then
        systemctl stop iptables
        systemctl disable iptables
    fi
}

delete_command()
{
    local vol=$(docker inspect -f '{{ (index .Mounts 0).Name }}' contrail_psql)

    docker stop contrail_command
    docker stop contrail_psql
    docker rm contrail_command
    docker rm contrail_psql
    docker rm contrail_command_deployer
    docker volume rm $vol
}

build()
{
    echo "Build bootstrap..."
    install_docker
    pull_image "$contrail_deployer_image"
    launch_deployer
    run_playbook "configure_instances.yml
            install_contrail.yml"

    #pull_image "$command_deployer_image"
    #launch_command
}

main()
{
    get_host_address

    case "$1" in
        launch-command)
            launch_command
            ;;
        delete-command)
            delete_command
            ;;
        *)
            build
            ;;
    esac
}

main "$@"
exit 0

